deepdiagnoses/deep_diagnose/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'deep_diagnose'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    # /home/
    # for finding nearby companies
    url(r'^home/$', views.home, name='find'),


    # /
    # for list of all companies
    url(r'^$', views.CompanyList.as_view(), name='company_list'),

    # /company/id(1,2..)
    # giving company details like tests and their price
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetails.as_view(), name='company_detail'),

    # /test_list/
    # for list of all tests
    url(r'^test_list/$', views.TestList.as_view(), name='test_list'),

    # /result/
    # shows result according to users location
    url(r'^result/$', views.result, name='result'),

    # /test/pk(1,2 ..)
    # for test details like about_test companies offering that test with price
    url(r'^tests/(?P<pk>[0-9]+)/$', views.TestDetail.as_view(), name='tests_detail'),

    url(r'^response/$', views.put_list, name='response'),

    path('response1/<str:abc>', views.show_results),

    path('profile/', views.profile, name='profile'),

    path('ordernow/', views.OrderNow.as_view(), name='ordernow'),

    path('thankyou/', views.thankyou, name='thankyou'),


 ]

deepdiagnoses/deepdiagnoses/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import  settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('deep_diagnose.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'),
         name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deepdiagnoses/deep_diagnose/models.py
from django.db import models
from django.urls import reverse


class CompanyDetail(models.Model):
    company_id = models.IntegerField(unique=True)
    company_name = models.CharField(max_length=250, unique=True)
    email_id = models.EmailField(unique=True)
    contact_no = models.IntegerField()
    address_line1 = models.CharField( max_length=125)
    city = models.CharField(max_length=125)
    state = models.CharField(max_length=125)
    logo = models.ImageField(upload_to='logo', blank=True)

    def __str__(self):
        return str(self.company_name)


class Tests(models.Model):
    test_name = models.CharField(max_length=125)
    test_details = models.CharField(max_length=250)

    def __str__(self):
        return str(self.test_name)

    class Meta:
        verbose_name = 'Tests'
        verbose_name_plural = 'Tests'


class CompanyTests(models.Model):
    company_name = models.ForeignKey(CompanyDetail, on_delete=models.CASCADE)
    tests = models.ForeignKey(Tests, on_delete=models.CASCADE)
    cost = models.IntegerField(default=0)

    def __str__(self):
        return str(self.company_name)

    class Meta:
        verbose_name_plural = 'CompanyTests'


class OrderInfo(models.Model):
    user_name = models.CharField(max_length=125)
    email_id = models.EmailField()
    age = models.IntegerField()
    address_line_1 = models.CharField(max_length=125)
    city = models.CharField(max_length=125)
    state = models.CharField(max_length=125)
    zip_code = models.IntegerField()
    phone_no = models.IntegerField()
    suitable_date = models.DateField()
    suitable_time = models.TimeField()
        

deepdiagnoses/deep_diagnose/forms.py
from django import forms


class Location(forms.Form):
    city = forms.CharField(
        required=True,
        label='City',
        max_length=32
    )
    state = forms.CharField(
        required=True,
        label='State',
        max_length=32
    )


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required=True,
        label='Username',
        max_length=32
    )
    email = forms.CharField(
        required=True,
        label='Email',
        max_length=32,
    )
    password = forms.CharField(
        required=True,
        label='Password',
        max_length=32,
        widget=forms.PasswordInput()
    )


class OrderNowForm(forms.Form):
    user_name = forms.CharField(max_length=125, required=True,
                                label='Username',)
    email_id = forms.EmailField(required=True,
                                label='Email Id',)
    age = forms.IntegerField()
    address_line_1 = forms.CharField(max_length=125, required=True,
                                     label='Address Line !',)
    city = forms.CharField(max_length=125, required=True,
                           label='City',)
    state = forms.CharField(max_length=125, required=True,
                            label='State',)
    zip_code = forms.IntegerField(required=True,
                                  label='Zip Code',)
    phone_no = forms.IntegerField(required=True,
                                  label='Phone Number', )
    suitable_date = forms.DateField(required=True,
                                    label='Suitable Date',)
    suitable_time = forms.TimeField(required=True,
                                    label='Suitable Time',)

deepdiagnoses/deep_diagnose/views.py
from .filters import CompanyFilter
from django.views import generic
from .models import CompanyDetail, Tests, CompanyTests, OrderInfo
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . forms import UserRegistrationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django import forms


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                raise forms.ValidationError('Looks like a username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'deep_diagnose/register.html', {'form': form})


# for finding companies in a particular area
def home(request):
    return render(request, 'deep_diagnose/user_location.html')

# for finding companies in a particular area
def home(request):
    return render(request, 'deep_diagnose/user_location.html')


# for showing result --->companies nearby
def result(request):
    company_list = CompanyDetail.objects.all().order_by('company_name')
    company_filter = CompanyFilter(request.GET, queryset=company_list)
    return render(request, 'deep_diagnose/company_list.html', {'filter': company_filter})


# gives list of all the companies
class CompanyList(generic.ListView):
    template_name = 'deep_diagnose/all_companies.html'
    context_object_name = 'all_companies'

    def get_queryset(self):
        return CompanyDetail.objects.all().order_by('company_name')


# gives details about the company->tests,price,contact info
class CompanyDetails(generic.DetailView):
    model = CompanyDetail
    template_name = 'deep_diagnose/company_details.html'
    context_object_name = 'company'


# list of all tests
class TestList(generic.ListView):
    template_name = 'deep_diagnose/all_tests.html'
    context_object_name = 'all_tests'

    def get_queryset(self):
        return Tests.objects.all().order_by('test_name')


# gives details about selected test
class TestDetail(generic.DetailView):
    model = Tests
    template_name = 'deep_diagnose/test_detail.html'
    context_object_name = 'test'


# returns company name on the basis search item in searchbox
def put_list(request):
    polls = Tests.objects.all()
    search_term=''
    if 'search' in request.GET:
        search_term = request.GET['search']
        polls = polls.filter(test_name__icontains=search_term)

    context = {'search_term': search_term, 'polls': polls, }
    return render(request, 'deep_diagnose/base.html', context)


def show_results(request, abc):
    # search=request.GET['search']
    polls = CompanyTests.objects.filter(tests__test_name=abc)
    """search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        polls = polls.filter(test__icontains=search_term)"""

    context = {
        'polls': polls
    }
    return render(request, 'deep_diagnose/base.html', context)


@login_required
def profile(request):
    return render(request, 'deep_diagnose/profile.html')


class OrderNow(CreateView):
    model = OrderInfo
    template_name = 'deep_diagnose/ordernow.html'
    fields = ['user_name', 'email_id','age','address_line_1','city','state','zip_code','phone_no',
              'suitable_date','suitable_time']
    success_url = reverse_lazy('deep_diagnose:find')


def thankyou(request):
    return render(request, 'deep_Diagnose/thankyou.html')

deepdiagnoses/deep_diagnose/templates/deep_diagnose/all_companies.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
{% for company in all_companies %}
<div class="title"><li><a href="{% url 'deep_diagnose:company_detail' company.id %}">{{company.company_name}}></a><br><br>
</div>
{% endfor %}
{% endblock %}

deepdiagnoses/deep_diagnose/templates/deep_diagnose/all_tests.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
{% for tests in all_tests %}
<a href="{% url 'deep_diagnose:tests_detail' pk=tests.pk %}">
{{ tests.test_name }}
</a>
<br>
{% endfor %}
{% endblock %}

deepdiagnoses/deep_diagnose/templates/deep_diagnose/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'deep_diagnose:find' %}">Home</a>
<br>
<a href="{% url 'deep_diagnose:company_list' %}">All Companies</a>
<br>
<a href="{% url 'deep_diagnose:test_list' %}">All Tests</a>
<br>
<a href="{% url 'deep_diagnose:ordernow' %}">
    order now
</a>
<form method="GET" action="" class="form-inline my-2 my-lg-0">
    <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Search"
            aria-label="Search"
            name="search"
            value="{{search_term}}">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<ul>
    {% for polls in polls %}
    <li><a href="/response1/{{polls}}"> {{ polls }} </a> </li>
    {% endfor %}
</ul>    

{% if user.is_authenticated %}
<br>
<a href="{% url 'logout' %}">
       Logout
</a>
<br>
<a href="{% url 'deep_diagnose:profile' %}">
      profile
</a>
<br>

<br>
{% else %}
<br>
<a href="{% url 'deep_diagnose:register' %}">
    register
</a>
<br>
<a href="{% url 'login' %}">
    Login
</a>
{% endif %}

<br><br><hr><hr>
{% block body %}

{% endblock %}
</body>
</html>

deepdiagnoses/deep_diagnose/templates/deep_diagnose/company_details.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<ul></ul>
{% for companytests in company.companytests_set.all %}
<li><a href="#">{{ companytests.tests }}</a>
<br>Rs-{{ companytests.cost }}
</li><br><br><br>
{% endfor %}
</ul>
{% endblock %}

deepdiagnoses/deep_diagnose/templates/deep_diagnose/company_list.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
<ul>
    {% for company in filter.qs %}
    <img src="{{company.logo.url }}" width="25%" height="45%">
    <br>
    <li><a href="{% url 'deep_diagnose:company_detail' company.id %}">{{company.company_name}}></a><br>
        {{ company.address_line1 }}
        <br>
        {{ company.city }} {{ company.state }}
        <br><br>

        {% endfor %}
</ul>
{% endblock %}

deepdiagnoses/deep_diagnose/templates/deep_diagnose/test_detail.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<ul></ul>
{% for companytests in test.companytests_set.all %}
<li>{{ company.logo.url }}
    <a href="#">{{ companytests.company_name }}</a>
    <br>Rs-{{ companytests.cost }}
    <br>

</li><br><br><br>
{% endfor %}
</ul>
{% endblock %}

deepdiagnoses/deep_diagnose/templates/deep_diagnose/user_location.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
<form method="get" action="{% url 'deep_diagnose:result' %}">
city
    <input type="text" name="city">
    state
    <input type="text" name="state">
    <button type="submit">Find</button>
</form>
{% endblock %}